/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ETH__factory } from "./ETH__factory";
export { Staking__factory } from "./Staking__factory";
export { Storage__factory } from "./Storage__factory";
