/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VDexStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_walletExits"
      | "addressConfig"
      | "callCoinPermit"
      | "decreasePositionRequestKeys"
      | "decreasePositionRequestKeysStart"
      | "decreasePositionRequests"
      | "decreasePositionsIndex"
      | "dispatcherWallets"
      | "g_status"
      | "increasePositionRequestKeys"
      | "increasePositionRequestKeysStart"
      | "increasePositionRequests"
      | "increasePositionsIndex"
      | "markets"
      | "nonce"
      | "numPairs"
      | "totalHelds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CancelSwapOrder"
      | "ChainPropagationPeriodChanged"
      | "CreateDecreasePosition"
      | "CreateIncreasePosition"
      | "Deposited"
      | "ExecuteDecreasePosition"
      | "ExecuteIncreasePosition"
      | "NewFactoryAddress"
      | "OrderBookTradeExecuted"
      | "OrderCreated"
      | "OrderNonceInvalidated"
      | "WalletExitCleared"
      | "WalletExited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_walletExits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addressConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callCoinPermit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decreasePositionRequestKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decreasePositionRequestKeysStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decreasePositionRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decreasePositionsIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatcherWallets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "g_status", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "increasePositionRequestKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increasePositionRequestKeysStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increasePositionRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increasePositionsIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "numPairs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalHelds",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_walletExits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callCoinPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreasePositionRequestKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreasePositionRequestKeysStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreasePositionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreasePositionsIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatcherWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "g_status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionRequestKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionRequestKeysStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionsIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numPairs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalHelds", data: BytesLike): Result;
}

export namespace CancelSwapOrderEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    account: AddressLike,
    baseAsset: AddressLike,
    quoteAsset: AddressLike,
    baseAssetAmount: BigNumberish,
    quoteAssetAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderHash: string,
    account: string,
    baseAsset: string,
    quoteAsset: string,
    baseAssetAmount: bigint,
    quoteAssetAmount: bigint
  ];
  export interface OutputObject {
    orderHash: string;
    account: string;
    baseAsset: string;
    quoteAsset: string;
    baseAssetAmount: bigint;
    quoteAssetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainPropagationPeriodChangedEvent {
  export type InputTuple = [
    previousValue: BigNumberish,
    newValue: BigNumberish
  ];
  export type OutputTuple = [previousValue: bigint, newValue: bigint];
  export interface OutputObject {
    previousValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreateDecreasePositionEvent {
  export type InputTuple = [
    account: AddressLike,
    depositToken: AddressLike,
    indexToken: AddressLike,
    collateralDelta: BigNumberish,
    sizeDelta: BigNumberish,
    isLong: boolean,
    receiver: AddressLike,
    acceptablePrice: BigNumberish,
    minOut: BigNumberish,
    executionFee: BigNumberish,
    index: BigNumberish,
    queueIndex: BigNumberish,
    blockNumber: BigNumberish,
    blockTime: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    depositToken: string,
    indexToken: string,
    collateralDelta: bigint,
    sizeDelta: bigint,
    isLong: boolean,
    receiver: string,
    acceptablePrice: bigint,
    minOut: bigint,
    executionFee: bigint,
    index: bigint,
    queueIndex: bigint,
    blockNumber: bigint,
    blockTime: bigint
  ];
  export interface OutputObject {
    account: string;
    depositToken: string;
    indexToken: string;
    collateralDelta: bigint;
    sizeDelta: bigint;
    isLong: boolean;
    receiver: string;
    acceptablePrice: bigint;
    minOut: bigint;
    executionFee: bigint;
    index: bigint;
    queueIndex: bigint;
    blockNumber: bigint;
    blockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreateIncreasePositionEvent {
  export type InputTuple = [
    account: AddressLike,
    depositToken: AddressLike,
    indexToken: AddressLike,
    amountIn: BigNumberish,
    minOut: BigNumberish,
    sizeDelta: BigNumberish,
    isLong: boolean,
    acceptablePrice: BigNumberish,
    executionFee: BigNumberish,
    index: BigNumberish,
    queueIndex: BigNumberish,
    blockNumber: BigNumberish,
    blockTime: BigNumberish,
    gasPrice: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    depositToken: string,
    indexToken: string,
    amountIn: bigint,
    minOut: bigint,
    sizeDelta: bigint,
    isLong: boolean,
    acceptablePrice: bigint,
    executionFee: bigint,
    index: bigint,
    queueIndex: bigint,
    blockNumber: bigint,
    blockTime: bigint,
    gasPrice: bigint
  ];
  export interface OutputObject {
    account: string;
    depositToken: string;
    indexToken: string;
    amountIn: bigint;
    minOut: bigint;
    sizeDelta: bigint;
    isLong: boolean;
    acceptablePrice: bigint;
    executionFee: bigint;
    index: bigint;
    queueIndex: bigint;
    blockNumber: bigint;
    blockTime: bigint;
    gasPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    assetAddress: AddressLike,
    quantityInPips: BigNumberish,
    newExchangeBalanceInPips: BigNumberish,
    newExchangeBalanceInAssetUnits: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    assetAddress: string,
    quantityInPips: bigint,
    newExchangeBalanceInPips: bigint,
    newExchangeBalanceInAssetUnits: bigint
  ];
  export interface OutputObject {
    wallet: string;
    assetAddress: string;
    quantityInPips: bigint;
    newExchangeBalanceInPips: bigint;
    newExchangeBalanceInAssetUnits: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecuteDecreasePositionEvent {
  export type InputTuple = [
    account: AddressLike,
    path: AddressLike[],
    indexToken: AddressLike,
    collateralDelta: BigNumberish,
    sizeDelta: BigNumberish,
    isLong: boolean,
    receiver: AddressLike,
    acceptablePrice: BigNumberish,
    minOut: BigNumberish,
    executionFee: BigNumberish,
    blockGap: BigNumberish,
    timeGap: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    path: string[],
    indexToken: string,
    collateralDelta: bigint,
    sizeDelta: bigint,
    isLong: boolean,
    receiver: string,
    acceptablePrice: bigint,
    minOut: bigint,
    executionFee: bigint,
    blockGap: bigint,
    timeGap: bigint
  ];
  export interface OutputObject {
    account: string;
    path: string[];
    indexToken: string;
    collateralDelta: bigint;
    sizeDelta: bigint;
    isLong: boolean;
    receiver: string;
    acceptablePrice: bigint;
    minOut: bigint;
    executionFee: bigint;
    blockGap: bigint;
    timeGap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecuteIncreasePositionEvent {
  export type InputTuple = [
    account: AddressLike,
    path: AddressLike[],
    indexToken: AddressLike,
    amountIn: BigNumberish,
    minOut: BigNumberish,
    sizeDelta: BigNumberish,
    isLong: boolean,
    acceptablePrice: BigNumberish,
    executionFee: BigNumberish,
    blockGap: BigNumberish,
    timeGap: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    path: string[],
    indexToken: string,
    amountIn: bigint,
    minOut: bigint,
    sizeDelta: bigint,
    isLong: boolean,
    acceptablePrice: bigint,
    executionFee: bigint,
    blockGap: bigint,
    timeGap: bigint
  ];
  export interface OutputObject {
    account: string;
    path: string[];
    indexToken: string;
    amountIn: bigint;
    minOut: bigint;
    sizeDelta: bigint;
    isLong: boolean;
    acceptablePrice: bigint;
    executionFee: bigint;
    blockGap: bigint;
    timeGap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewFactoryAddressEvent {
  export type InputTuple = [factory: AddressLike];
  export type OutputTuple = [factory: string];
  export interface OutputObject {
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderBookTradeExecutedEvent {
  export type InputTuple = [
    buyWallet: AddressLike,
    sellWallet: AddressLike,
    buyerInputUpdate: BigNumberish,
    sellerInputUpdate: BigNumberish,
    buyerOutputUpdate: BigNumberish,
    sellerOutputUpdate: BigNumberish,
    takerSide: BigNumberish
  ];
  export type OutputTuple = [
    buyWallet: string,
    sellWallet: string,
    buyerInputUpdate: bigint,
    sellerInputUpdate: bigint,
    buyerOutputUpdate: bigint,
    sellerOutputUpdate: bigint,
    takerSide: bigint
  ];
  export interface OutputObject {
    buyWallet: string;
    sellWallet: string;
    buyerInputUpdate: bigint;
    sellerInputUpdate: bigint;
    buyerOutputUpdate: bigint;
    sellerOutputUpdate: bigint;
    takerSide: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    makerAccountOwner: AddressLike,
    baseAsset: AddressLike,
    quoteAsset: AddressLike,
    orderType: BigNumberish,
    baseAssetAmount: BigNumberish,
    quoteAssetAmount: BigNumberish,
    orderSide: BigNumberish,
    expiration: BigNumberish,
    nonce: BigNumberish,
    isLong: boolean
  ];
  export type OutputTuple = [
    orderHash: string,
    makerAccountOwner: string,
    baseAsset: string,
    quoteAsset: string,
    orderType: bigint,
    baseAssetAmount: bigint,
    quoteAssetAmount: bigint,
    orderSide: bigint,
    expiration: bigint,
    nonce: bigint,
    isLong: boolean
  ];
  export interface OutputObject {
    orderHash: string;
    makerAccountOwner: string;
    baseAsset: string;
    quoteAsset: string;
    orderType: bigint;
    baseAssetAmount: bigint;
    quoteAssetAmount: bigint;
    orderSide: bigint;
    expiration: bigint;
    nonce: bigint;
    isLong: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderNonceInvalidatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    nonce: BigNumberish,
    timestampInMs: BigNumberish,
    effectiveBlockNumber: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    nonce: bigint,
    timestampInMs: bigint,
    effectiveBlockNumber: bigint
  ];
  export interface OutputObject {
    wallet: string;
    nonce: bigint;
    timestampInMs: bigint;
    effectiveBlockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletExitClearedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletExitedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    effectiveBlockNumber: BigNumberish
  ];
  export type OutputTuple = [wallet: string, effectiveBlockNumber: bigint];
  export interface OutputObject {
    wallet: string;
    effectiveBlockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VDexStorage extends BaseContract {
  connect(runner?: ContractRunner | null): VDexStorage;
  waitForDeployment(): Promise<this>;

  interface: VDexStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _walletExits: TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { exists: boolean; effectiveBlockNumber: bigint }],
    "view"
  >;

  addressConfig: TypedContractMethod<
    [],
    [[string, string] & { factory: string; wETH: string }],
    "view"
  >;

  callCoinPermit: TypedContractMethod<[], [string], "view">;

  decreasePositionRequestKeys: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  decreasePositionRequestKeysStart: TypedContractMethod<[], [bigint], "view">;

  decreasePositionRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        account: string;
        depositToken: string;
        indexToken: string;
        collateralDelta: bigint;
        sizeDelta: bigint;
        isLong: boolean;
        receiver: string;
        acceptablePrice: bigint;
        minOut: bigint;
        executionFee: bigint;
        blockNumber: bigint;
        blockTime: bigint;
        withdrawETH: boolean;
      }
    ],
    "view"
  >;

  decreasePositionsIndex: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  dispatcherWallets: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  g_status: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  increasePositionRequestKeys: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  increasePositionRequestKeysStart: TypedContractMethod<[], [bigint], "view">;

  increasePositionRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        account: string;
        depositToken: string;
        indexToken: string;
        amountIn: bigint;
        minOut: bigint;
        sizeDelta: bigint;
        isLong: boolean;
        acceptablePrice: bigint;
        executionFee: bigint;
        blockNumber: bigint;
        blockTime: bigint;
        hasCollateralInETH: boolean;
      }
    ],
    "view"
  >;

  increasePositionsIndex: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint, bigint] & {
        pool: string;
        token0: string;
        token1: string;
        marginLimit: bigint;
        priceUpdater: string;
        pool0Insurance: bigint;
        pool1Insurance: bigint;
      }
    ],
    "view"
  >;

  nonce: TypedContractMethod<[], [bigint], "view">;

  numPairs: TypedContractMethod<[], [bigint], "view">;

  totalHelds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_walletExits"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { exists: boolean; effectiveBlockNumber: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "addressConfig"
  ): TypedContractMethod<
    [],
    [[string, string] & { factory: string; wETH: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "callCoinPermit"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decreasePositionRequestKeys"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "decreasePositionRequestKeysStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreasePositionRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        account: string;
        depositToken: string;
        indexToken: string;
        collateralDelta: bigint;
        sizeDelta: bigint;
        isLong: boolean;
        receiver: string;
        acceptablePrice: bigint;
        minOut: bigint;
        executionFee: bigint;
        blockNumber: bigint;
        blockTime: bigint;
        withdrawETH: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decreasePositionsIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dispatcherWallets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "g_status"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "increasePositionRequestKeys"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "increasePositionRequestKeysStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "increasePositionRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        account: string;
        depositToken: string;
        indexToken: string;
        amountIn: bigint;
        minOut: bigint;
        sizeDelta: bigint;
        isLong: boolean;
        acceptablePrice: bigint;
        executionFee: bigint;
        blockNumber: bigint;
        blockTime: bigint;
        hasCollateralInETH: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "increasePositionsIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint, bigint] & {
        pool: string;
        token0: string;
        token1: string;
        marginLimit: bigint;
        priceUpdater: string;
        pool0Insurance: bigint;
        pool1Insurance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "numPairs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalHelds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "CancelSwapOrder"
  ): TypedContractEvent<
    CancelSwapOrderEvent.InputTuple,
    CancelSwapOrderEvent.OutputTuple,
    CancelSwapOrderEvent.OutputObject
  >;
  getEvent(
    key: "ChainPropagationPeriodChanged"
  ): TypedContractEvent<
    ChainPropagationPeriodChangedEvent.InputTuple,
    ChainPropagationPeriodChangedEvent.OutputTuple,
    ChainPropagationPeriodChangedEvent.OutputObject
  >;
  getEvent(
    key: "CreateDecreasePosition"
  ): TypedContractEvent<
    CreateDecreasePositionEvent.InputTuple,
    CreateDecreasePositionEvent.OutputTuple,
    CreateDecreasePositionEvent.OutputObject
  >;
  getEvent(
    key: "CreateIncreasePosition"
  ): TypedContractEvent<
    CreateIncreasePositionEvent.InputTuple,
    CreateIncreasePositionEvent.OutputTuple,
    CreateIncreasePositionEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "ExecuteDecreasePosition"
  ): TypedContractEvent<
    ExecuteDecreasePositionEvent.InputTuple,
    ExecuteDecreasePositionEvent.OutputTuple,
    ExecuteDecreasePositionEvent.OutputObject
  >;
  getEvent(
    key: "ExecuteIncreasePosition"
  ): TypedContractEvent<
    ExecuteIncreasePositionEvent.InputTuple,
    ExecuteIncreasePositionEvent.OutputTuple,
    ExecuteIncreasePositionEvent.OutputObject
  >;
  getEvent(
    key: "NewFactoryAddress"
  ): TypedContractEvent<
    NewFactoryAddressEvent.InputTuple,
    NewFactoryAddressEvent.OutputTuple,
    NewFactoryAddressEvent.OutputObject
  >;
  getEvent(
    key: "OrderBookTradeExecuted"
  ): TypedContractEvent<
    OrderBookTradeExecutedEvent.InputTuple,
    OrderBookTradeExecutedEvent.OutputTuple,
    OrderBookTradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderNonceInvalidated"
  ): TypedContractEvent<
    OrderNonceInvalidatedEvent.InputTuple,
    OrderNonceInvalidatedEvent.OutputTuple,
    OrderNonceInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "WalletExitCleared"
  ): TypedContractEvent<
    WalletExitClearedEvent.InputTuple,
    WalletExitClearedEvent.OutputTuple,
    WalletExitClearedEvent.OutputObject
  >;
  getEvent(
    key: "WalletExited"
  ): TypedContractEvent<
    WalletExitedEvent.InputTuple,
    WalletExitedEvent.OutputTuple,
    WalletExitedEvent.OutputObject
  >;

  filters: {
    "CancelSwapOrder(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      CancelSwapOrderEvent.InputTuple,
      CancelSwapOrderEvent.OutputTuple,
      CancelSwapOrderEvent.OutputObject
    >;
    CancelSwapOrder: TypedContractEvent<
      CancelSwapOrderEvent.InputTuple,
      CancelSwapOrderEvent.OutputTuple,
      CancelSwapOrderEvent.OutputObject
    >;

    "ChainPropagationPeriodChanged(uint256,uint256)": TypedContractEvent<
      ChainPropagationPeriodChangedEvent.InputTuple,
      ChainPropagationPeriodChangedEvent.OutputTuple,
      ChainPropagationPeriodChangedEvent.OutputObject
    >;
    ChainPropagationPeriodChanged: TypedContractEvent<
      ChainPropagationPeriodChangedEvent.InputTuple,
      ChainPropagationPeriodChangedEvent.OutputTuple,
      ChainPropagationPeriodChangedEvent.OutputObject
    >;

    "CreateDecreasePosition(address,address,address,uint256,uint256,bool,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CreateDecreasePositionEvent.InputTuple,
      CreateDecreasePositionEvent.OutputTuple,
      CreateDecreasePositionEvent.OutputObject
    >;
    CreateDecreasePosition: TypedContractEvent<
      CreateDecreasePositionEvent.InputTuple,
      CreateDecreasePositionEvent.OutputTuple,
      CreateDecreasePositionEvent.OutputObject
    >;

    "CreateIncreasePosition(address,address,address,uint256,uint256,uint256,bool,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CreateIncreasePositionEvent.InputTuple,
      CreateIncreasePositionEvent.OutputTuple,
      CreateIncreasePositionEvent.OutputObject
    >;
    CreateIncreasePosition: TypedContractEvent<
      CreateIncreasePositionEvent.InputTuple,
      CreateIncreasePositionEvent.OutputTuple,
      CreateIncreasePositionEvent.OutputObject
    >;

    "Deposited(address,address,uint64,uint64,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "ExecuteDecreasePosition(address,address[],address,uint256,uint256,bool,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ExecuteDecreasePositionEvent.InputTuple,
      ExecuteDecreasePositionEvent.OutputTuple,
      ExecuteDecreasePositionEvent.OutputObject
    >;
    ExecuteDecreasePosition: TypedContractEvent<
      ExecuteDecreasePositionEvent.InputTuple,
      ExecuteDecreasePositionEvent.OutputTuple,
      ExecuteDecreasePositionEvent.OutputObject
    >;

    "ExecuteIncreasePosition(address,address[],address,uint256,uint256,uint256,bool,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ExecuteIncreasePositionEvent.InputTuple,
      ExecuteIncreasePositionEvent.OutputTuple,
      ExecuteIncreasePositionEvent.OutputObject
    >;
    ExecuteIncreasePosition: TypedContractEvent<
      ExecuteIncreasePositionEvent.InputTuple,
      ExecuteIncreasePositionEvent.OutputTuple,
      ExecuteIncreasePositionEvent.OutputObject
    >;

    "NewFactoryAddress(address)": TypedContractEvent<
      NewFactoryAddressEvent.InputTuple,
      NewFactoryAddressEvent.OutputTuple,
      NewFactoryAddressEvent.OutputObject
    >;
    NewFactoryAddress: TypedContractEvent<
      NewFactoryAddressEvent.InputTuple,
      NewFactoryAddressEvent.OutputTuple,
      NewFactoryAddressEvent.OutputObject
    >;

    "OrderBookTradeExecuted(address,address,uint256,uint256,uint256,uint256,uint8)": TypedContractEvent<
      OrderBookTradeExecutedEvent.InputTuple,
      OrderBookTradeExecutedEvent.OutputTuple,
      OrderBookTradeExecutedEvent.OutputObject
    >;
    OrderBookTradeExecuted: TypedContractEvent<
      OrderBookTradeExecutedEvent.InputTuple,
      OrderBookTradeExecutedEvent.OutputTuple,
      OrderBookTradeExecutedEvent.OutputObject
    >;

    "OrderCreated(bytes32,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderNonceInvalidated(address,uint128,uint128,uint256)": TypedContractEvent<
      OrderNonceInvalidatedEvent.InputTuple,
      OrderNonceInvalidatedEvent.OutputTuple,
      OrderNonceInvalidatedEvent.OutputObject
    >;
    OrderNonceInvalidated: TypedContractEvent<
      OrderNonceInvalidatedEvent.InputTuple,
      OrderNonceInvalidatedEvent.OutputTuple,
      OrderNonceInvalidatedEvent.OutputObject
    >;

    "WalletExitCleared(address)": TypedContractEvent<
      WalletExitClearedEvent.InputTuple,
      WalletExitClearedEvent.OutputTuple,
      WalletExitClearedEvent.OutputObject
    >;
    WalletExitCleared: TypedContractEvent<
      WalletExitClearedEvent.InputTuple,
      WalletExitClearedEvent.OutputTuple,
      WalletExitClearedEvent.OutputObject
    >;

    "WalletExited(address,uint256)": TypedContractEvent<
      WalletExitedEvent.InputTuple,
      WalletExitedEvent.OutputTuple,
      WalletExitedEvent.OutputObject
    >;
    WalletExited: TypedContractEvent<
      WalletExitedEvent.InputTuple,
      WalletExitedEvent.OutputTuple,
      WalletExitedEvent.OutputObject
    >;
  };
}
