/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracleWrapper,
  IOracleWrapperInterface,
} from "../../../contracts/interfaces/IOracleWrapper";

const _abi = [
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOracleWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleWrapperInterface {
    return new Interface(_abi) as IOracleWrapperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOracleWrapper {
    return new Contract(address, _abi, runner) as unknown as IOracleWrapper;
  }
}
