/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICallCoinPermit } from "./ICallCoinPermit";
export type { ILPool } from "./ILPool";
export type { IOracleWrapper } from "./IOracleWrapper";
export type { IPoolFactory } from "./IPoolFactory";
export type { IVDex } from "./IVDex";
export type { IVault } from "./IVault";
export type { IWBNB } from "./IWBNB";
