/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Role, RoleInterface } from "../../../contracts/role/Role";

const _abi = [
  {
    inputs: [],
    name: "CONFIG_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CONTROLLER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FEE_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FROZEN_ORDER_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIQUIDATION_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MARKET_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORDER_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICING_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROLE_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61030661003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061009d5760003560e01c8063c66aade111610070578063c66aade1146100d4578063cf7fb1d0146100dc578063d391014b146100e4578063ee0fc121146100ec578063f13c5a4b146100f457600080fd5b80635fac3ab1146100a25780636ed0f620146100bc5780639ecff617146100c4578063a0074230146100cc575b600080fd5b6100aa6100fc565b60405190815260200160405180910390f35b6100aa610146565b6100aa610176565b6100aa6101a8565b6100aa6101df565b6100aa610210565b6100aa61023e565b6100aa61026c565b6100aa61029a565b60405160200161012d906020808252600d908201526c26a0a925a2aa2fa5a2a2a822a960991b604082015260600190565b6040516020818303038152906040528051906020012081565b60405160200161012d906020808252600c908201526b27a92222a92fa5a2a2a822a960a11b604082015260600190565b60405160200161012d906020808252600e908201526d282924a1a4a723afa5a2a2a822a960911b604082015260600190565b60405160200161012d90602080825260139082015272232927ad22a72fa7a92222a92fa5a2a2a822a960691b604082015260600190565b60405160200161012d906020808252600d908201526c21a7a72324a3afa5a2a2a822a960991b604082015260600190565b60405160200161012d906020808252600a90820152692322a2afa5a2a2a822a960b11b604082015260600190565b60405160200161012d906020808252600a90820152692927a622afa0a226a4a760b11b604082015260600190565b60405160200161012d906020808252600a908201526921a7a72a2927a62622a960b11b604082015260600190565b60405160200161012d906020808252601290820152712624a8aaa4a220aa24a7a72fa5a2a2a822a960711b60408201526060019056fea26469706673582212201b07e6e16ce54bf63e1d6415a90c0af67b696089715b070508ed8b89f36c9b0f64736f6c63430008120033";

type RoleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RoleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Role__factory extends ContractFactory {
  constructor(...args: RoleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Role & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Role__factory {
    return super.connect(runner) as Role__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RoleInterface {
    return new Interface(_abi) as RoleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Role {
    return new Contract(address, _abi, runner) as unknown as Role;
  }
}
