/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Storage {
  export type StakeStruct = {
    stakeToken: AddressLike;
    convertRate: BigNumberish;
    interestRate: BigNumberish;
    isActive: boolean;
  };

  export type StakeStructOutput = [
    stakeToken: string,
    convertRate: bigint,
    interestRate: bigint,
    isActive: boolean
  ] & {
    stakeToken: string;
    convertRate: bigint;
    interestRate: bigint;
    isActive: boolean;
  };

  export type UserStakeStruct = {
    user: AddressLike;
    stakeToken: AddressLike;
    stakeAmount: BigNumberish;
    interestRate: BigNumberish;
    receiveAmount: BigNumberish;
    interestAmount: BigNumberish;
    startDate: BigNumberish;
    interestWithdrew: BigNumberish;
    withdrawTime: BigNumberish;
    period: BigNumberish;
    completed: boolean;
  };

  export type UserStakeStructOutput = [
    user: string,
    stakeToken: string,
    stakeAmount: bigint,
    interestRate: bigint,
    receiveAmount: bigint,
    interestAmount: bigint,
    startDate: bigint,
    interestWithdrew: bigint,
    withdrawTime: bigint,
    period: bigint,
    completed: boolean
  ] & {
    user: string;
    stakeToken: string;
    stakeAmount: bigint;
    interestRate: bigint;
    receiveAmount: bigint;
    interestAmount: bigint;
    startDate: bigint;
    interestWithdrew: bigint;
    withdrawTime: bigint;
    period: bigint;
    completed: boolean;
  };
}

export interface StorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "OahToken"
      | "calculateTotalInterest"
      | "stakes"
      | "userStakes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "StakesChanged"
      | "UserClaimed"
      | "UserStaked"
      | "UserWithdrew"
  ): EventFragment;

  encodeFunctionData(functionFragment: "OahToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateTotalInterest",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "userStakes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "OahToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStakes", data: BytesLike): Result;
}

export namespace StakesChangedEvent {
  export type InputTuple = [_stakes: Storage.StakeStruct[]];
  export type OutputTuple = [_stakes: Storage.StakeStructOutput[]];
  export interface OutputObject {
    _stakes: Storage.StakeStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserClaimedEvent {
  export type InputTuple = [id: BigNumberish, claimedAmount: BigNumberish];
  export type OutputTuple = [id: bigint, claimedAmount: bigint];
  export interface OutputObject {
    id: bigint;
    claimedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserStakedEvent {
  export type InputTuple = [
    id: BigNumberish,
    _userStake: Storage.UserStakeStruct
  ];
  export type OutputTuple = [
    id: bigint,
    _userStake: Storage.UserStakeStructOutput
  ];
  export interface OutputObject {
    id: bigint;
    _userStake: Storage.UserStakeStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserWithdrewEvent {
  export type InputTuple = [
    id: BigNumberish,
    _userStake: Storage.UserStakeStruct
  ];
  export type OutputTuple = [
    id: bigint,
    _userStake: Storage.UserStakeStructOutput
  ];
  export interface OutputObject {
    id: bigint;
    _userStake: Storage.UserStakeStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Storage extends BaseContract {
  connect(runner?: ContractRunner | null): Storage;
  waitForDeployment(): Promise<this>;

  interface: StorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  OahToken: TypedContractMethod<[], [string], "view">;

  calculateTotalInterest: TypedContractMethod<
    [period: BigNumberish, interestRate: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        stakeToken: string;
        convertRate: bigint;
        interestRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  userStakes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        user: string;
        stakeToken: string;
        stakeAmount: bigint;
        interestRate: bigint;
        receiveAmount: bigint;
        interestAmount: bigint;
        startDate: bigint;
        interestWithdrew: bigint;
        withdrawTime: bigint;
        period: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "OahToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateTotalInterest"
  ): TypedContractMethod<
    [period: BigNumberish, interestRate: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        stakeToken: string;
        convertRate: bigint;
        interestRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userStakes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        user: string;
        stakeToken: string;
        stakeAmount: bigint;
        interestRate: bigint;
        receiveAmount: bigint;
        interestAmount: bigint;
        startDate: bigint;
        interestWithdrew: bigint;
        withdrawTime: bigint;
        period: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "StakesChanged"
  ): TypedContractEvent<
    StakesChangedEvent.InputTuple,
    StakesChangedEvent.OutputTuple,
    StakesChangedEvent.OutputObject
  >;
  getEvent(
    key: "UserClaimed"
  ): TypedContractEvent<
    UserClaimedEvent.InputTuple,
    UserClaimedEvent.OutputTuple,
    UserClaimedEvent.OutputObject
  >;
  getEvent(
    key: "UserStaked"
  ): TypedContractEvent<
    UserStakedEvent.InputTuple,
    UserStakedEvent.OutputTuple,
    UserStakedEvent.OutputObject
  >;
  getEvent(
    key: "UserWithdrew"
  ): TypedContractEvent<
    UserWithdrewEvent.InputTuple,
    UserWithdrewEvent.OutputTuple,
    UserWithdrewEvent.OutputObject
  >;

  filters: {
    "StakesChanged(tuple[])": TypedContractEvent<
      StakesChangedEvent.InputTuple,
      StakesChangedEvent.OutputTuple,
      StakesChangedEvent.OutputObject
    >;
    StakesChanged: TypedContractEvent<
      StakesChangedEvent.InputTuple,
      StakesChangedEvent.OutputTuple,
      StakesChangedEvent.OutputObject
    >;

    "UserClaimed(uint256,uint256)": TypedContractEvent<
      UserClaimedEvent.InputTuple,
      UserClaimedEvent.OutputTuple,
      UserClaimedEvent.OutputObject
    >;
    UserClaimed: TypedContractEvent<
      UserClaimedEvent.InputTuple,
      UserClaimedEvent.OutputTuple,
      UserClaimedEvent.OutputObject
    >;

    "UserStaked(uint256,tuple)": TypedContractEvent<
      UserStakedEvent.InputTuple,
      UserStakedEvent.OutputTuple,
      UserStakedEvent.OutputObject
    >;
    UserStaked: TypedContractEvent<
      UserStakedEvent.InputTuple,
      UserStakedEvent.OutputTuple,
      UserStakedEvent.OutputObject
    >;

    "UserWithdrew(uint256,tuple)": TypedContractEvent<
      UserWithdrewEvent.InputTuple,
      UserWithdrewEvent.OutputTuple,
      UserWithdrewEvent.OutputObject
    >;
    UserWithdrew: TypedContractEvent<
      UserWithdrewEvent.InputTuple,
      UserWithdrewEvent.OutputTuple,
      UserWithdrewEvent.OutputObject
    >;
  };
}
